name: Release Pipeline

on:
  push: {}
  workflow_dispatch:
    inputs:
      version:
        description: "Release Version"
        required: true
        type: string

jobs:
  release-pipeline:
    name: Release Pipeline
    runs-on: windows-latest
    env:
      CERT_NAME: cert.pfx
    steps:
      - uses: actions/checkout@v4
      - name: Set up Dotnet tools
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Run Core.Test
        run: dotnet test .\src\DevOpsDaysTasks.Core.Tests

      - name: Run Integration.Test
        run: dotnet test .\src\DevOpsDaysTasks.IntegrationTests

      - name: Publish Build
        env:
          VERSION: ${{ inputs.version || '0.0.0' }}
        run: dotnet publish -c Release src\DevOpsDaysTasks.UI\ -o DevOpsDaysTasks /p:Version=${{ inputs.version }} /p:VersionName=IndieBurger

      - name: Publish Build
        run: dotnet publish -c Release src\DevOpsDaysTasks.UI\ -o DevOpsDaysTasks /p:Version=${{ inputs.version }} /p:VersionName=IndieBurger

      - name: Checkout external files
        uses: actions/checkout@v4
        with:
          repository: martinzimmermann/DevOpsDaysGraz2025-ExternalFiles
          path: ExternalFiles

      - name: Copy Template
        run: |
          mkdir DevOpsDaysTasks\Templates
          copy ExternalFiles\default-tasks.xml DevOpsDaysTasks\Templates\

      - name: Copy Template
        run: |
          mkdir DevOpsDaysTasks\Help
          copy ExternalFiles\Help.pdf DevOpsDaysTasks\Help\

      - name: Create Cert
        run: |
          $base64 = "${{ secrets.SIGN_CERTIFICATE_PFX_BASE64}}"
          $content = [System.Convert]::FromBase64String($base64)
          Set-Content ${{ env.CERT_NAME }} -Value $content -AsByteStream

      - name: Sign Release
        run: .\scripts\sign.ps1 .\DevOpsDaysTasks\DevOpsDaysTasks.UI.exe -PfxFile ${{ env.CERT_NAME }} -PfxPassword Password

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DevOpsDaysTasks
          path: DevOpsDaysTasks

      # Create ZIP for Release
      - name: Create ZIP
        run: |
          Compress-Archive -Path DevOpsDaysTasks\* -DestinationPath DevOpsDaysTasks.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{ inputs.version }}
        with:
          name: DevOpsDaysTasks
          tag_name: ${{ inputs.version }}
          files: DevOpsDaysTasks.zip
