name: Release Pipeline

on:
  push: {}

jobs:
  release-pipeline:
    name: Release Pipeline
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Dotnet tools
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Run Core.Test
        run: dotnet test .\src\DevOpsDaysTasks.Core.Tests
